jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      QT_QPA_PLATFORM: offscreen
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONDONTWRITEBYTECODE: "1"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps (Ubuntu only)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 \
            libopengl0 \
            libxkbcommon0 \
            libxcb1 \
            libx11-xcb1 \
            libxrandr2 \
            libxext6 \
            libxi6 \
            libcups2 \
            libdbus-1-3 \
            libnss3 \
            fonts-dejavu-core

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Ruff format (check)
        shell: bash
        run: |
          ruff format --check .
          ruff check .

      - name: Run tests
        shell: bash
        run: |
          pytest --cov=pymd --cov-report=term-missing -q
