name: pre-commit autofix

on:
  pull_request:
    branches: [ master, development ]
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: |
          python -m pip install -U pip
          pip install pre-commit

      - name: Run pre-commit (autofix)
        run: pre-commit run --all-files || true

      - name: Commit & push fixes (if any)
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "chore(pre-commit): auto-fix style"
            git push
          fi
